### ISSUE TITLE
Minibuffer completion and highlighted item legibility

### ISSUE THREAD

**Issue by mmarshall540** [qhga/shanty-themes#1]
This is a beautiful and practical high contrast theme.

I use vertico with prescient and marginalia for minibuffer completion, and I'm noticing a minor issue with legibility of the highlighted item.

In the first column of the result, the typed part of the highlighted item is hard to read. So for example, if I enter "M-x custo", I get "customize-variable" highlighted as the first item. But the typed portion ("custo") is barely readable. I think it's cyan on pink. The un-typed part of the selection, "mize-variable", is readable, since the foreground color changes to black when selected with the pink highlighter.

Similarly, the information provided by marginalia doesn't change color when highlighted, so it's also hard to make out.

Thank you for making this!

Edit: Forgot to mention I'm using the shanty-dark theme.

**Comment by qhga** [comment]
@mmarshall540 I hope this commit fixes your issue. Feel free to report back if not. Thanks for reporting and trying out this theme!
