### ISSUE TITLE
What is the font you're using in the screenshot?

### ISSUE THREAD

**Issue by hewhocannotbetamed** [qhga/shanty-themes#2]
Couldn't resist. Doesn't seem to be any other means of communicating with you, anyways. I'm addicted to bitmapped fonts and the one you're using is tantalizing.

Also, what package is responsible for the lovely headers for the .cpp and .py files? I'm sifting through lsp.el, since I suspect it to be a feature I wasn't aware of.

**Comment by qhga** [comment]
Hey @hewhocannotbetamed,

The font is called Ttyp0. Here is a link: https://people.mpi-inf.mpg.de/~uwe/misc/uw-ttyp0/. I also love this font (:
The headers are indeed part of the lsp package: https://emacs-lsp.github.io/lsp-mode/page/settings/headerline/

I would recommend, to disable the diagnostics though:

```emacs-lisp
(setq lsp-headerline-breadcrumb-enable-diagnostics nil)
```

**Comment by hewhocannotbetamed** [comment]
Much appreciated!
