### ISSUE TITLE
Shanty themes loading twice on startup, even if not the enabled theme.

### ISSUE THREAD

**Issue by mmarshall540** [qhga/shanty-themes#3]
I wasn't sure if this was normal behavior for themes, so I confirmed that the other theme packages I have installed (e.g. modus-themes, doom-themes, almost-mono-themes) are only loading when they're the enabled theme.

This appears at the top of my \*Messages\* buffer on every startup, even if a different theme is enabled.

    Loading /var/home/mmarshall540/.config/emacs/elpa/shanty-themes-20220405.1126/shanty-themes.el (source)...done
    Loading /var/home/mmarshall540/.config/emacs/elpa/shanty-themes-20220405.1126/shanty-themes.el (source)...done

It looks like the autoloads generated from "shanty-themes-dark-theme.el" and "shanty-themes-light-theme.el" each cause the main package file to load.

Towards the end of each of those files is the following:

    ;;;###autoload
    (when load-file-name
      (load-file (concat (file-name-directory load-file-name) "shanty-themes.el")))

What I think is happening:

At installation time, package.el reads those 2 autoload declaration and adds them to "shanty-themes-autoloads.el".

Then on every Emacs startup, package.el evaluates the autoloads for all packages. At the time "shanty-themes-autoloads.el" is loaded, the `load-file-name` variable would be equal to the name of that file, which tells it to load "shanty-themes.el" twice regardless of whether one of those themes is being loaded or not.

**Comment by qhga** [comment]
@mmarshall540 Thanks for reporting this! Looks like a bug. I am going to look into it in the next couple days. Since I use `straight` I might not have noticed it.

**Comment by mmarshall540** [comment]
Unfortunately, I don't know much about how themes get loaded/autoloaded. 

I tried to simply remove the autoloads from "shanty-themes-dark.el" and "shanty-themes-light.el", thinking maybe the autoload from "shanty-themes.el" would be enough.

After reinstalling, the themes were still listed in the Customize interface, but attempting to select them simply reverted to the default Emacs theme.

**Comment by qhga** [comment]
@mmarshall540 Thanks again for reporting. If you like, report back if the package now functions as expected. Have a great day!

**Comment by mmarshall540** [comment]
Yep, much improved. Thanks @qhga !
